# Site settings
title: dev cogs
description: dev cogs is a software development shop specializing in WordPress, Python, and Golang development.
url: https://devcogs.github.io/
github_username: devcogs

# Build settings
markdown: kramdown
permalink: ordinal
